# Generated by Django 6.0 on 2025-12-18 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitems',
            old_name='quality',
            new_name='quantity',
        ),
    ]
