# Generated by Django 6.0 on 2025-12-22 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_cartitems_variations'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitems',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
