# Generated by Django 6.0 on 2026-01-09 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_remove_order_payment_orderitem_delete_payment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
